### ISSUE TITLE
Consider model casts when generating transformers

### ISSUE THREAD

**Issue by cerbero90** [rexlabsio/smokescreen-laravel-php#15]
@lachlankrautz correctly pointed out we should also consider the `$casts` property to determine the properties type of models when we generate transformers from CLI.

**Comment by jodiedunlop** [comment]
Hey, just clarifying this one: 

Do you mean with regards to declaring their format in the transformer?

If you have casts on the model, and do not declare format in the transformer then it would be automatically using the casted value that eloquent returns when you access a property... in which case declaring it in the transformer might essentially mean it is being cast/formatted twice.

**Comment by lachlankrautz** [comment]
Yeah sounds fine, I was thinking your were casting based on the schema
which might not match. You'd probably want to just leave it if there is a
cast entry.
