### ISSUE TITLE
Allow passing class string instead of transformer instance

### ISSUE THREAD

**Issue by jodiedunlop** [rexlabsio/smokescreen-laravel-php#16]
The `transform()` `collection()` and `item()` methods, take an optional transformer instance as the second method. When omitted, the transformer resolver is used to try and find a matching transformer and instantiate it via the laravel app container.

It would be nice if you could pass `MyTransformer::class` (string) as the second argument, meaning that it should be instantiated via laravel's app container.

```
public function index()
{
    return Smokescreen::transform(User::all(), UserTransformer::class);
}
```

**Comment by lachlankrautz** [comment]
Implemented in [2.0.0](https://github.com/rexlabsio/smokescreen-laravel-php/releases/tag/2.0.0)
